config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'home/index'
  resources :users, except: [:new, :destroy]

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace :admin do
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    resources :users
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  validates :email, uniqueness: true, presence: true
  validates :name, presence: true
  # if: -> { new_record? || changes[:crypted_password] }
  # パスワード以外のプロフィール項目を(メールアドレスや名前)を更新したい場合にパスワードの入力を省略
  validates :password, length: { minimum: 5 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController
  skip_before_action :require_login
  def new
  end

  def create
    @user = login(params[:email], params[:password])
    if @user && @user.admin?
      redirect_to admin_users_url, success: "ログインに成功しました"
    else
      flash.now[:danger] = "ログインに失敗しました"
      render :new
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update!(user_params)
    redirect_to admin_users_url, success: '更新に成功しました'
  end

  def destroy
    user = User.find(params[:id])
    user.destroy!
    redirect_to admin_users_url, notice: 'ユーザーを削除しました'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
  # :require_login sorceryが作成するメソッド。ログインしてない時not_authenticatedメソッドを発火する
  before_action :require_login
  def not_authenticated
    redirect_to login_url, danger: 'ログインしてください'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login
  def new
  end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_to user_url(@user), success: "ログインに成功しました"
    else
      flash.now[:danger] = "ログインに失敗しました"
      render :new
    end
  end

  def destroy
    logout
    redirect_back_or_to root_path, success: "ログアウトしました"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:create, :new]
  def new
    @user = User.new

    if logged_in?
      redirect_to root_url
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to user_url(@user), success: 'サインアップに成功しました'
    else
      flash.now[:alert] = "サインアップに失敗しました"
      render :new
    end
  end

  def show
    # adminがtrue,もしくは自分のページでない場合,自分の詳細画面にリダイレクト
    @user = User.find(params[:id])
    unless current_user.admin || current_user.id == @user.id
      redirect_to user_path(current_user.id), danger: '権限がありません'
    end
  end

  def edit
    @user = User.find(params[:id])
    unless current_user.admin || current_user.id == @user.id
      redirect_to user_path(current_user.id), danger: '権限がありません'
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update!(user_params)
    redirect_to user_url(@user), success: '更新に成功しました'
  end
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="has-text-centered">
  <h1 class="title">詳細</h1>
  <%= form_with model: @user, url: user_path(@user), local: true, method: :patch do |f| %>
    <div class="field ">
      <%= f.label :name, '名前', class: 'label has-text-left' %>
      <%= f.text_field :name, class: 'input' %>
    </div>
    <div class="field">
      <%= f.label :email, 'メールアドレス', class: 'label has-text-left' %>
      <%= f.email_field :email, class: 'input' %>
    </div>
    <div class="field">
      <%= f.label :password, 'パスワード', class: 'label has-text-left' %>
      <%= f.password_field :password, class: 'input' %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation, 'パスワード確認', class: 'label has-text-left' %>
      <%= f.password_field :password_confirmation, class: 'input' %>
    </div>
    <div class="control">
      <%= f.submit "更新", class: 'button is-info is-rounded is-medium mt-5' %>
    </div>
  <% end %>
</div>

app/views/admin/users/index.html.erb
<h1 class="title has-text-centered">ユーザー一覧</h1>

<table class="table" align="center">
  <thead>
  <tr>
    <th>名前</th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <% @users.each do |user| %>
  <tbody>
    <tr>
      <td><%= link_to user.name, user_path(user) %></td>
      <td><%= link_to '編集', edit_admin_user_path(user), class: 'button is-success' %></td>
      <td><%= link_to '削除', admin_user_path(user), method: :delete, data: {confirm: 'ユーザーを削除しますか？'}, class: 'button is-danger' %></td>
    </tr>
  </tbody>
  <% end %>
</table>

app/views/home/index.html.erb
<h1 class="title">home</h1>

<%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mojist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= render 'shared/flash_messages' %>
    <section class="section">
      <div class="container">
        <%= yield %>
      </div>
    </section>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="notification is-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to 'Mojist', root_path, class: 'title'%>
  </div>
  <div class="navbar-menu">
    <div class="navbar-end">
      <div class="navbar-item">
        <% if current_user %>
          <%= link_to 'ログアウト', logout_path, method: :delete, class: 'button is-danger' %>
        <% else %>
          <%= link_to 'ログイン', login_path, class: 'button is-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/users/new.html.erb
<div class="has-text-centered">
  <h1 class="title">新規登録</h1>
  <%= form_with model: @user, url: users_path, local: true do |f| %>
    <div class="field ">
      <%= f.label :name, '名前', class: 'label has-text-left' %>
      <%= f.text_field :name, class: 'input' %>
    </div>
    <div class="field">
      <%= f.label :email, 'メールアドレス', class: 'label has-text-left' %>
      <%= f.email_field :email, class: 'input' %>
    </div>
    <div class="field">
      <%= f.label :password, 'パスワード', class: 'label has-text-left' %>
      <%= f.password_field :password, class: 'input' %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation, 'パスワード確認', class: 'label has-text-left' %>
      <%= f.password_field :password_confirmation, class: 'input' %>
    </div>
    <div class="control">
      <%= f.submit "登録", class: 'button is-info is-rounded is-medium mt-5' %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h1 class="title">
  ユーザー詳細
</h1>

<div>
  名前: <%= @user.name %>
</div>

<%= link_to '編集', edit_user_path, class: 'button is-success is-rounded is-medium mt-5' %>